apiVersion: batch/v1
kind: Job
metadata:
  name: job1
  namespace: example
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu:latest
        command: ["sh", "-c"]
        args:
        - |
          echo "sleep 60"
          echo "echo Hi"
      restartPolicy: Never
  backoffLimit: 4
