apiVersion: batch/v1
kind: Job
metadata:
  name: job2
  namespace: example
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu:latest
        command: ["echo", "Hello, Kubernetes!"]        
      restartPolicy: Never
  backoffLimit: 4
