apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-pre-deploy
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: my-app
  path: "./network-function-flux/pre-deploy/"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
