apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: network-function-ms2
  namespace: example
spec:
  dependsOn:
    - name: network-function-ms1
  interval: 1m
  chart:
    spec:
      chart: ./network-function-flux/helmcharts/helloworld-go-1.3.12.tgz
      version: '1.3.12'
      sourceRef:
        kind: GitRepository
        name: my-app
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: example
  valuesFrom:
  - kind: ConfigMap
    name: network-function-values
    valuesKey: values.yaml
