kind: ConfigMap
metadata: # kpt-merge: example/network-function-values
  name: network-function-values
  namespace: example
apiVersion: v1
data:
  values.yaml: |+
    replicas: 2
    image:
      tag: latest
