apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: network-function-ms2
  namespace: example
spec:
  kubeConfig:
    secretRef:
      name: target-kubeconfig
  dependsOn:
    - name: network-function-ms1
  interval: 1m
  chart:
    spec:
      chart: ./network-function-flux/helmcharts/hello-world-1.0.0.tgz
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: my-app
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: example
  valuesFrom:
  - kind: ConfigMap
    name: network-function-values
    valuesKey: values.yaml
