apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: network-function-gitrepo
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/Nordix/nordix-nephio-packages
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts
