apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: network-function-ms1
  namespace: example
spec:
  interval: 1m
  chart:
    spec:
      chart: ./network-function-flux/helmcharts/helloworld-1.0.0.tgz
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: my-app
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: example
  valuesFrom:
  - kind: ConfigMap
    name: network-function-values
    valuesKey: values.yaml
